### ISSUE TITLE
Support inline expressions

### ISSUE THREAD

**Issue by martin-braun** [daniel-sc/bash-shell-to-bat-converter#56] opened 2022-08-11 08:16 UTC
```bash
echo $(echo "test")
```

converts to: 

```bat
@echo off

echo "%undefined%"
```

Even worse:

```bash
echo "$(echo "$(echo "test")")"
```

throws:

```none
parse error: SyntaxError: Unclosed $(
```

**Comment by daniel-sc** [comment] 2022-11-24 08:07
duplicate of #51

**Closed by daniel-sc** 2022-11-24 08:07 UTC
Labels: duplicate
